import { useState } from 'react'
import './App.css'

const wishes = [
  ['Смелости', 'Чтобы мечты не боялись становиться планами, а ты всегда верила в себя.'],
  ['Вдохновения', 'Чтобы каждый день находил повод улыбнуться, творить и пробовать новое.'],
  ['Счастья', 'Настоящего, большого, тёплого и именно твоего.'],
  ['Верных людей', 'Чтобы рядом были те, кто ценит тебя, понимает и бережёт.'],
  ['Ярких моментов', 'Чтобы жизнь была наполнена маленькими приключениями и добрыми чудесами.'],
  ['Исполнения желаний', 'Пусть даже самые смелые мечты однажды станут твоей реальностью.'],
]

function App() {
  const [opened, setOpened] = useState(false)
  const [heart, setHeart] = useState(false)
  const [cakeClicked, setCakeClicked] = useState(false)
  const [loveOpened, setLoveOpened] = useState(false)
  const [starsFound, setStarsFound] = useState([])
  const findStar = (id) => setStarsFound((stars) => stars.includes(id) ? stars : [...stars, id])
  return <main className={opened ? 'page celebration' : 'page'}>
    <div className="grain" /><div className="glow glow-one" /><div className="glow glow-two" />
    <nav><span className="monogram">M</span><span className="nav-text">особенный день</span><span className="date">19 · 09 · 2011</span></nav>
    <section className="hero-section"><div className="eyebrow"><span /> С ДНЁМ РОЖДЕНИЯ <span /></div><p className="for-you">для самой замечательной</p><h1>Малика<span className="spark">✦</span></h1><p className="intro">Сегодня мир стал чуточку ярче —<br />ведь однажды в нём появилась ты.</p>
      <div className="orbital-card"><i className="orbit orbit-a" /><i className="orbit orbit-b" /><span className="star s1">✦</span><span className="star s2">✧</span><span className="star s3">✦</span><button className={cakeClicked ? 'cake cake-clicked' : 'cake'} onClick={() => setCakeClicked(!cakeClicked)} aria-label="Загадать желание и задуть свечи"><div className="flames"><b>{cakeClicked ? '✧' : '♥'}</b><b>{cakeClicked ? '✧' : '♥'}</b><b>{cakeClicked ? '✧' : '♥'}</b></div><div className="candles"><i /><i /><i /></div><div className="frosting">✿</div><div className="cake-body"><span>✦</span><span>✦</span><span>✦</span></div><div className="plate" /></button><p>{cakeClicked ? <>Желание загадано —<br /><strong>оно обязательно сбудется ✦</strong></> : <>Нажми на торт и<br /><strong>загадай желание</strong></>}</p>{cakeClicked && <div className="cake-hearts"><i>♥</i><i>♥</i><i>♥</i><i>♥</i><i>♥</i></div>}</div>
    </section>
    <section className={loveOpened ? 'love-letter love-opened' : 'love-letter'}><div className="love-rays" /><span className="love-heart">♥</span><p className="section-label">СЛОВА, КОТОРЫЕ ХОЧЕТСЯ СКАЗАТЬ</p><h2>Малика,<br /><em>{loveOpened ? 'я тебя люблю.' : 'у меня есть секрет.'}</em></h2>{loveOpened ? <><p>Ты стала для меня очень важным человеком. Мне нравится твоя улыбка, твой характер, твой смех — и просто то, какая ты есть. Ты — моё самое тёплое совпадение.</p><div className="love-signature">всегда твой <span>♥</span></div></> : <button className="letter-button" onClick={() => setLoveOpened(true)}><span>Нажми, чтобы прочитать</span><b>✦</b></button>}{loveOpened && <div className="love-particles" aria-hidden="true">{Array.from({ length: 15 }, (_, i) => <i key={i} style={{ '--p': i }}>♥</i>)}</div>}</section>
    <section className={starsFound.length === 3 ? 'constellation solved' : 'constellation'}><p className="section-label">МАЛЕНЬКАЯ ИГРА ДЛЯ ТЕБЯ</p><h2>Найди три звезды<br /><em>и загадай желание.</em></h2><p className="constellation-tip">Нажми на каждую сияющую звёздочку</p><div className="star-map"><i className="line line-one" /><i className="line line-two" />{[0, 1, 2].map((id) => <button key={id} className={starsFound.includes(id) ? `magic-star found star-${id}` : `magic-star star-${id}`} onClick={() => findStar(id)} aria-label="Найти звезду">{starsFound.includes(id) ? '♥' : '✦'}</button>)}<div className="constellation-message">{starsFound.length === 3 ? <><strong>Желание принято звёздами.</strong><span>Пусть у тебя всегда будет причина улыбаться, смело мечтать и верить в себя. Пусть рядом будут добрые люди, дни будут светлыми, а всё самое заветное однажды тихо станет реальностью.</span></> : `${starsFound.length} / 3 звезды найдены`}</div></div></section>
    <section className="wishes"><p className="section-label">МОИ ПОЖЕЛАНИЯ ТЕБЕ</p><div className="wish-grid">{wishes.map(([title, text], index) => <article className="wish" key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{text}</p></article>)}</div></section>
    <section className="support-note"><span className="quote-mark">“</span><p>И помни: что бы ни случилось, <strong>я всегда рядом с тобой.</strong><br />В твоих победах, в новых мечтах и даже в самые обычные дни.<br /><small>Ты для меня по-настоящему особенная. И мне очень повезло, что ты есть в моей жизни.</small></p><span className="quote-mark closing">”</span></section>
    <section className="memories"><div><p className="section-label">МЕСТО ДЛЯ ТЁПЛЫХ СЛОВ</p><h2>Моменты, которые<br /><em>хочется хранить.</em></h2><p className="memory-text">Даже без фотографий здесь остаётся самое важное: добрые слова, тёплые чувства и маленькие причины улыбнуться.</p></div><div className="memory-grid"><article className="memory-card"><b>01</b><span>Твоя улыбка</span><p>Пусть она появляется чаще и делает каждый день немного светлее.</p></article><article className="memory-card"><b>02</b><span>Лучший день</span><p>Пусть впереди будет много дней, которые захочется вспоминать с радостью.</p></article><article className="memory-card"><b>03</b><span>Наша дружба</span><p>Спасибо за твою искренность, тепло и за то, что с тобой спокойно на душе.</p></article><article className="memory-card"><b>04</b><span>Ещё одна мечта</span><p>Пусть каждая мечта найдёт свой путь к тебе и красиво исполнится.</p></article></div></section>
    <section className="reasons"><p className="section-label">ПОЧЕМУ ТЫ ОСОБЕННАЯ</p><h2>В тебе есть то, что<br /><em>нельзя не заметить.</em></h2><div className="reason-grid"><article><b>01</b><span>Твоя улыбка</span><p>Она делает даже самый обычный день намного светлее.</p></article><article><b>02</b><span>Твоя искренность</span><p>С тобой хочется быть собой и говорить обо всём.</p></article><article><b>03</b><span>Твоя мечта</span><p>Я верю, что у тебя получится всё, чего ты захочешь.</p></article></div></section>
    <section className="gift-section"><div className="gift-copy"><p className="section-label">МАЛЕНЬКИЙ СЕКРЕТ</p><h2>Для тебя есть<br /><em>подарок.</em></h2><p>Открой его — там спрятано<br />немного праздничного чуда и одно важное признание.</p></div><button className="gift-button" onClick={() => setOpened(true)} aria-label="Открыть подарок"><span className="ribbon-v" /><span className="ribbon-h" /><span className="bow">♡</span><span className="box-lid" /><strong>{opened ? 'Ура!' : 'Открыть'}</strong></button></section>
    {opened && <section className="message-card"><span className="card-star">✦</span><p>Ты делаешь этот мир для меня теплее одной своей улыбкой. Оставайся такой же светлой, искренней и удивительной. Я хочу, чтобы ты знала: <strong>ты мне очень нравишься, ты для меня особенная, и я тебя люблю.</strong></p><button className={heart ? 'heart active' : 'heart'} onClick={() => setHeart(!heart)}>{heart ? '♥' : '♡'} <span>от всего сердца</span></button></section>}
    {opened && <div className="confetti" aria-hidden="true">{Array.from({ length: 28 }, (_, i) => <i key={i} style={{ '--i': i }} />)}</div>}<footer>С любовью и самыми тёплыми мыслями <span>♥</span></footer>
  </main>
}
export default App
